name: Deploy to AWS Lambda
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      # Steps for deployment
      - name: Validate CloudFormation Template
        run: |
          sam validate
      - name: Build Docker image
        run: |
          sam build --debug
      - name: Package & Upload to S3 Bucket
        run: |
          sam package --s3-bucket websocket-server-bucket --region eu-central-1 --output-template-file out.yml
      - name: Deploy to AWS Lambda
        run: |
          sam deploy --template-file out.yml --stack-name websocket-server-stack --region eu-central-1 --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM
